# Generated by Django 5.0.3 on 2024-03-28 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultados',
            name='sala',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='users.salas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salas',
            name='nome_sala',
            field=models.CharField(default='Sem Nome', max_length=30),
            preserve_default=False,
        ),
    ]
