# Generated by Django 5.0.3 on 2024-03-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_salas_image_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salas',
            name='image_room',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
