# Generated by Django 5.0.3 on 2024-03-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_salas_image_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salas',
            name='image_room',
        ),
    ]
